### ISSUE TITLE
MagicHome Wifi - Bulb-Controller Schedule Error

### ISSUE THREAD

**Issue by jglemza** [adamkempenich/hubitat#4]
The calls to the schedule method appear to be broken with the latest Hubitat firmware (2.2.0.122).

`java.lang.RuntimeException: CronExpression '0/60 * * * * ? *' is invalid. on line 289 (initialize)`

I'm not sure how to fix this issue. For the time being I've set mine to run every minute by hard coding it on lines 289 and 316 of **MagicHome Wifi — Bulb-Controller (Dimmable).groovy**.

For example, `schedule("0 * * ? * *", connectDevice, [data: [firstRun: false]])` and `schedule("0 * * ? * *", refresh)` work as intended.

Thanks

**Comment by adamkempenich** [comment]
Fixing now. 1-59 are valid numbers for the range.

**Comment by adamkempenich** [comment]
Thank you!
